name : who_wins

on:
  push:
  pull_request:

jobs:
  rock_paper_scissors:
    name: Check whose commit wins
    runs-on: ubuntu-latest

    steps:
      - name: I hope you win!
        run: |
          options='🪨✂📄'
          echo "choice=${options:$(( RANDOM % ${#options} )):1}" >> $GITHUB_ENV

      - name: ${{ github.actor }} has chosen ${{env.choice}}
        run: echo -n
